spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  rabbitmq:
    host: localhost
    port: 5672
    password: temprabbit
    username: temprabbit

product:
  create:
    queue:
      name: product-create
  list:
    queue:
      name: product-list

logging:
  level:
    org: INFO
