spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  rabbitmq:
    host: localhost
    port: 5672
    password: temprabbit
    username: temprabbit

product:
  queues:
    creation-name: product-create
    list-name: product-list

logging:
  level:
    org: INFO
