spring:
  datasource:
    url: jdbc:mysql://localhost/skt
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    include: common

logging:
  level:
    org: INFO
